# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  HOME: /
  ARCHIVES: archives

social:
  email: memoryhonest@protonmail.com
  github: memoryhonest/nCovmemory-en
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

